### ISSUE TITLE
unable to view snippets list

### ISSUE THREAD

**Issue by DaniAkash** [kswedberg/atom-jquery#3]
everything is working but the snippets list in package readme is not properly being displayed

image: http://postimg.org/image/eqfni84lr/

other installed packages: atom-bootstrap3, color-picker, codeigniter, minimap, terminal-plus, nodejs-snippets

**Comment by kswedberg** [comment]
It looks like this problem is caused by the combination of a few very long snippet bodies (the plugin ones) and some styles set by Atom (`.settings-view .table td { padding-left: 1%; padding-right: 1%; }`). If you Open Your Stylesheet and change the padding to 2px or similar, it should fix it. I'll also look for a way to work around the super long snippets.

**Comment by DaniAkash** [comment]
Thanks for the suggestion, I'll change the stylesheet value... Also received the latest update but the issue doesn't seem to be fixed yet :(

**Comment by kswedberg** [comment]
I just added a stylesheet to the package to fix the display of the snippets list. Please let me know if that takes care of it for you.

**Comment by DaniAkash** [comment]
Nice work!! The problem is completly fixed :D thanks a lot!!!
